name: Setup
description: Install Node, Bun, and project dependencies

runs:
  using: composite
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@3d267786b128fe76c2f16a390aa2448b815359f3 # v2

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc

    - name: Install dependencies
      shell: bash
      run: bun install --frozen-lockfile
