// Auto-generated by @storybook/react-native metro plugin at build time.
// This declaration satisfies TypeScript when the file doesn't exist yet.
declare const view: import("@storybook/react-native").View;
export { view };
