#!/usr/bin/env node
/**
 * Build theme CSS files from theme JSON definitions
 */
import StyleDictionary from "style-dictionary";
import { readdir } from "node:fs/promises";
import { join, basename } from "node:path";

// Mapping from theme JSON structure to original CSS variable names
const pathMappings = {
  "surface.background": "background",
  "surface.foreground": "foreground",
  "surface.card": "card",
  "surface.card-foreground": "card-foreground",
  "surface.popover": "popover",
  "surface.popover-foreground": "popover-foreground",
  "surface.muted": "muted",
  "surface.muted-foreground": "muted-foreground",
  "interactive.primary": "primary",
  "interactive.primary-foreground": "primary-foreground",
  "interactive.secondary": "secondary",
  "interactive.secondary-foreground": "secondary-foreground",
  "interactive.accent": "accent",
  "interactive.accent-foreground": "accent-foreground",
  "feedback.destructive": "destructive",
  "feedback.destructive-foreground": "destructive-foreground",
  "feedback.success": "success",
  "feedback.success-foreground": "success-foreground",
  "feedback.warning": "warning",
  "feedback.warning-foreground": "warning-foreground",
  "feedback.info": "info",
  "feedback.info-foreground": "info-foreground",
  "form.border": "border",
  "form.input": "input",
  "form.ring": "ring",
  "typography.font-family": "font-family",
  "typography.text-primary": "text-primary",
  "typography.text-secondary": "text-secondary",
  "typography.text-disabled": "text-disabled",
  "typography.text-inverse": "text-inverse",
  "aliases.bg-primary": "bg-primary",
  "aliases.bg-secondary": "bg-secondary",
  "aliases.bg-disabled": "bg-disabled",
  "aliases.border-color": "border-color",
  "aliases.border-color-focus": "border-color-focus",
  "aliases.border-width": "border-width",
  "aliases.border-radius-sm": "border-radius-sm",
  "aliases.border-radius-md": "border-radius-md",
  "aliases.border-radius-lg": "border-radius-lg",
  "aliases.border-radius-xl": "border-radius-xl",
};

// Register theme format
StyleDictionary.registerFormat({
  name: "css/ob-theme-class",
  format: ({ dictionary, options }) => {
    const themeName = options.themeName;
    const className = `.ob-${themeName}-theme`;

    let output = `/* ${themeName} theme */\n${className} {\n`;

    const processTokens = (tokens, prefix = "") => {
      Object.entries(tokens).forEach(([key, value]) => {
        if (key.startsWith("$")) return; // Skip metadata

        const path = prefix ? `${prefix}.${key}` : key;

        if (typeof value === "object" && value !== null && !value.$value) {
          processTokens(value, path);
        } else {
          const tokenValue = value.$value || value;
          // Use mapping if available, otherwise convert dots to dashes
          const varName = pathMappings[path] || path.replace(/\./g, "-");
          output += `  --ob-${varName}: ${tokenValue};\n`;
        }
      });
    };

    // Process the theme object
    const themeData = dictionary.tokens.theme || dictionary.tokens;
    processTokens(themeData);

    output += "}\n";
    return output;
  },
});

async function buildThemes() {
  const themesDir = join(import.meta.dirname, "src/themes");
  const outputFile = join(import.meta.dirname, "build/css/themes.css");

  const files = await readdir(themesDir);
  const themeFiles = files.filter(
    (f) => f.endsWith(".json") && f !== "light.json",
  );

  let allThemesCSS = `/**
 * OpenBadges UI — Theme Overrides
 *
 * Auto-generated by Style Dictionary from design-tokens package.
 * DO NOT EDIT DIRECTLY.
 *
 * Available themes:
 *   .ob-dark-theme              – Dark mode
 *   .ob-high-contrast-theme     – WCAG AAA contrast
 *   .ob-large-text-theme        – Larger fonts and line heights
 *   .ob-dyslexia-friendly-theme – OpenDyslexic font, cream bg, extra spacing
 *   .ob-low-vision-theme        – Atkinson Hyperlegible, high contrast, large text
 *   .ob-low-info-theme          – Simplified palette, reduced distractions
 *   .ob-autism-friendly-theme   – Predictable layout, muted palette, no shadows
 */

/* Reduced motion preference */
@media (prefers-reduced-motion: reduce) {
  :root {
    --ob-transition-fast: 0ms;
    --ob-transition-normal: 0ms;
    --ob-transition-slow: 0ms;
  }
}

`;

  for (const file of themeFiles) {
    const themeName = basename(file, ".json");

    const sd = new StyleDictionary({
      source: [join(themesDir, file)],
      platforms: {
        css: {
          transformGroup: "css",
          buildPath: "build/css/",
          files: [
            {
              destination: `theme-${themeName}.css`,
              format: "css/ob-theme-class",
              options: { themeName },
            },
          ],
        },
      },
    });

    await sd.buildAllPlatforms();

    // Read the generated file and append to combined output
    const { readFile } = await import("node:fs/promises");
    const themeCSS = await readFile(
      join(import.meta.dirname, `build/css/theme-${themeName}.css`),
      "utf-8",
    );
    allThemesCSS += themeCSS + "\n";
  }

  // Write combined themes file
  const { writeFile } = await import("node:fs/promises");
  await writeFile(outputFile, allThemesCSS);

  console.log("Built themes.css with all theme variants");
}

buildThemes().catch(console.error);
