import { StyleSheet } from "react-native-unistyles";
import type { ComposedTheme } from "../../themes/compose";

export const styles = StyleSheet.create((theme) => ({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  scrollContent: {
    padding: theme.space[4],
    paddingBottom: theme.space[12],
    gap: theme.space[6],
  },
  hero: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: theme.space[4],
  },
  heroText: {
    flex: 1,
  },
  heroTitle: {
    fontSize: theme.size["3xl"],
    lineHeight: theme.lineHeight["3xl"],
    fontWeight: theme.fontWeight.bold,
    fontFamily: theme.fontFamily.headline,
    color: theme.colors.text,
  },
  heroSubtitle: {
    marginTop: theme.space[2],
    fontSize: theme.size.md,
    lineHeight: theme.lineHeight.md,
    fontFamily: theme.fontFamily.body,
    color: theme.colors.textSecondary,
  },
  section: {},
  sectionTitle: {
    fontSize: theme.size["2xl"],
    lineHeight: theme.lineHeight["2xl"],
    fontWeight: theme.fontWeight.bold,
    fontFamily: theme.fontFamily.headline,
    color: theme.colors.text,
    marginBottom: theme.space[4],
  },
  sectionDesc: {
    fontSize: theme.size.sm,
    lineHeight: theme.lineHeight.sm,
    fontFamily: theme.fontFamily.body,
    color: theme.colors.textSecondary,
    marginBottom: theme.space[4],
  },
  stack: {
    gap: theme.space[3],
  },
  row: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: theme.space[3],
  },
  themeInfo: {
    backgroundColor: theme.colors.backgroundSecondary,
    padding: theme.space[3],
    borderRadius: theme.radius.md,
  },
  themeInfoText: {
    fontSize: theme.size.md,
    lineHeight: theme.lineHeight.md,
    fontFamily: theme.fontFamily.body,
    color: theme.colors.text,
  },
  overviewBlock: (bg: string, textColor: string, t: ComposedTheme) => ({
    backgroundColor: bg,
    borderRadius: t.radius.lg,
    borderWidth: 1,
    borderColor: t.colors.border,
    padding: t.space[4],
  }),
  narrativeTitle: (t: ComposedTheme) => ({
    fontSize: t.size.xl,
    lineHeight: t.lineHeight.xl,
    fontWeight: t.fontWeight.bold,
    fontFamily: t.fontFamily.headline,
    color: t.colors.text,
  }),
  overviewCode: (t: ComposedTheme) => ({
    marginTop: t.space[2],
    fontSize: t.size.xs,
    lineHeight: t.lineHeight.xs,
    fontFamily: t.fontFamily.mono,
    color: t.colors.textSecondary,
  }),
  displayBlock: (t: ComposedTheme) => ({
    backgroundColor: t.colors.backgroundSecondary,
    borderRadius: t.radius.lg,
    borderWidth: 1,
    borderColor: t.colors.border,
    padding: t.space[5],
    marginBottom: t.space[3],
  }),
  displayText: (
    t: ComposedTheme,
    sizeKey: keyof ComposedTheme["size"],
    color?: string,
  ) => {
    const fontSize = t.size[sizeKey];
    const lineHeightMap = t.lineHeight as Record<string, number>;
    const lineHeight =
      lineHeightMap[sizeKey as string] ?? Math.round(fontSize * 1.1);
    return {
      fontSize,
      lineHeight,
      fontWeight: t.fontWeight.black,
      fontFamily: t.fontFamily.headline,
      color: color ?? t.colors.text,
    };
  },
  sectionBlock: (t: ComposedTheme) => ({
    flex: 1,
    minWidth: 200,
    borderWidth: 1,
    borderColor: t.colors.border,
    borderRadius: t.radius.lg,
    padding: t.space[4],
    backgroundColor: t.colors.background,
  }),
  sectionBlockText: (t: ComposedTheme) => ({
    marginTop: t.space[2],
    fontSize: t.size.sm,
    lineHeight: t.lineHeight.sm,
    fontFamily: t.fontFamily.body,
    color: t.colors.textSecondary,
  }),
  typeSamples: (t: ComposedTheme) => ({
    borderWidth: 1,
    borderColor: t.colors.border,
    borderRadius: t.radius.lg,
    padding: t.space[4],
    backgroundColor: t.colors.backgroundSecondary,
  }),
  typeHeadline: (t: ComposedTheme) => ({
    fontSize: t.size["2xl"],
    lineHeight: t.lineHeight["2xl"],
    fontWeight: t.fontWeight.bold,
    fontFamily: t.fontFamily.headline,
    color: t.colors.text,
  }),
  previewBody: (t: ComposedTheme) => ({
    marginTop: t.space[2],
    fontSize: t.size.sm,
    lineHeight: t.lineHeight.sm,
    fontFamily: t.fontFamily.body,
    color: t.colors.text,
  }),
  previewMono: (t: ComposedTheme) => ({
    marginTop: t.space[2],
    fontSize: t.size.sm,
    lineHeight: t.lineHeight.sm,
    fontFamily: t.fontFamily.mono,
    color: t.colors.text,
  }),
  swatchCard: (t: ComposedTheme) => ({
    flexGrow: 1,
    minWidth: 180,
    borderWidth: 1,
    borderColor: t.colors.border,
    borderRadius: t.radius.md,
    padding: t.space[3],
    backgroundColor: t.colors.backgroundSecondary,
  }),
  swatchText: (t: ComposedTheme) => ({
    fontSize: t.size.sm,
    lineHeight: t.lineHeight.sm,
    fontFamily: t.fontFamily.mono,
    color: t.colors.text,
  }),
  previewCard: (t: ComposedTheme) => ({
    borderWidth: 1,
    borderColor: t.colors.border,
    borderRadius: t.radius.lg,
    padding: t.space[4],
    backgroundColor: t.colors.background,
    marginBottom: t.space[4],
  }),
  previewTitle: (t: ComposedTheme) => ({
    fontSize: t.size["2xl"],
    lineHeight: t.lineHeight["2xl"],
    fontWeight: t.fontWeight.bold,
    fontFamily: t.fontFamily.headline,
    color: t.colors.text,
    marginBottom: t.space[1],
  }),
  previewSubtitle: (t: ComposedTheme) => ({
    fontSize: t.size.sm,
    lineHeight: t.lineHeight.sm,
    fontFamily: t.fontFamily.body,
    color: t.colors.textSecondary,
    marginBottom: t.space[4],
  }),
  previewSection: {
    marginBottom: theme.space[4],
  },
  previewSectionTitle: (t: ComposedTheme) => ({
    fontSize: t.size.lg,
    lineHeight: t.lineHeight.lg,
    fontWeight: t.fontWeight.semibold,
    fontFamily: t.fontFamily.headline,
    color: t.colors.text,
    marginBottom: t.space[2],
  }),
  previewSectionDesc: (t: ComposedTheme) => ({
    fontSize: t.size.sm,
    lineHeight: t.lineHeight.sm,
    fontFamily: t.fontFamily.body,
    color: t.colors.textSecondary,
    marginBottom: t.space[3],
  }),
  previewGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: theme.space[3],
  },
  narrativeCard: (bg: string, textColor: string, t: ComposedTheme) => ({
    flexGrow: 1,
    minWidth: 200,
    backgroundColor: bg,
    borderRadius: t.radius.lg,
    borderWidth: 1,
    borderColor: t.colors.border,
    padding: t.space[4],
  }),
  badgeLabel: (textColor: string, bg: string, t: ComposedTheme) => ({
    alignSelf: "flex-start",
    backgroundColor: bg,
    color: textColor,
    borderRadius: t.radius.pill,
    paddingHorizontal: t.space[2],
    paddingVertical: t.space[1],
    fontSize: t.size.xs,
    lineHeight: t.lineHeight.xs,
    fontWeight: t.fontWeight.semibold,
    fontFamily: t.fontFamily.body,
    marginBottom: t.space[2],
  }),
  storyLabelRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: theme.space[2],
    marginBottom: theme.space[2],
  },
  storyLabel: (bg: string, textColor: string, t: ComposedTheme) => ({
    backgroundColor: bg,
    color: textColor,
    borderRadius: t.radius.pill,
    paddingHorizontal: t.space[2],
    paddingVertical: t.space[1],
    fontSize: t.size.xs,
    lineHeight: t.lineHeight.xs,
    fontWeight: t.fontWeight.semibold,
    fontFamily: t.fontFamily.body,
  }),
  accentPaletteRow: (count: number) => ({
    flexDirection: "row",
    flexWrap: "wrap",
    gap: theme.space[3],
  }),
  accentSwatch: (bg: string, t: ComposedTheme) => ({
    flexGrow: 1,
    minWidth: 140,
    backgroundColor: bg,
    borderRadius: t.radius.md,
    borderWidth: 1,
    borderColor: t.colors.border,
    padding: t.space[3],
    justifyContent: "flex-end",
  }),
  accentText: (textColor: string, t: ComposedTheme) => ({
    color: textColor,
    fontSize: t.size.sm,
    lineHeight: t.lineHeight.sm,
    fontFamily: t.fontFamily.body,
    fontWeight: t.fontWeight.semibold,
  }),
  landingBlock: (bg: string, textColor: string, t: ComposedTheme) => ({
    backgroundColor: bg,
    borderRadius: t.radius.lg,
    borderWidth: 1,
    borderColor: t.colors.border,
    paddingVertical: t.space[6],
    paddingHorizontal: t.space[5],
    marginBottom: t.space[4],
  }),
  landingCtaRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: theme.space[2],
    marginTop: theme.space[3],
  },
}));
